### PR TITLE
Add Adafruit Feather ESP32 V2 board

### PR DESCRIPTION
**Pull request by maxgerhardt**
For https://github.com/espressif/arduino-esp32/tree/master/variants/adafruit_feather_esp32_v2 with the default settings from https://github.com/espressif/arduino-esp32/blob/68daea4a4a03ca0e10b84c3a34e40a371df11e69/boards.txt#L5725-L5794

### CODE REVIEW

**Comment by maxgerhardt** [comment]
No PSRAM? This is the V2 board not an S2 board. https://www.adafruit.com/product/5400

https://github.com/espressif/arduino-esp32/blob/68daea4a4a03ca0e10b84c3a34e40a371df11e69/boards.txt#L5776-L5777

**Comment by Jason2866** [comment]
Thx! removed PSRAM fixes since S2 has no known issues here.
There are "some" board definitions which are just wrong. Copy&Paste.
The fixes are only needed for ESP32 v1 and some v2

**Comment by Jason2866** [comment]
Ahh, true. Will add!

**Comment by maxgerhardt** [comment]
But it's not a S2 chip! :O From adafruit's site

>"[ESP32­ Pico ­Mini 02](https://cdn-shop.adafruit.com/product-files/5400/esp32-pico-mini-02_datasheet_en.pdf)"

>"ESP32-PICO-V3-02 embedded, Xtensa dual-core 32-bit LX6 microprocessor, up to 240 MHz"

The S2 would be single core 

https://www.espressif.com/en/products/socs/esp32-s2

**Comment by Jason2866** [comment]
If it is a ESP32-PICO-V3-02 than the fix is definitly NOT needed

**Comment by maxgerhardt** [comment]
Alright then, the [boards.txt](https://github.com/espressif/arduino-esp32/blob/68daea4a4a03ca0e10b84c3a34e40a371df11e69/boards.txt#L5776-L5777) might want to be fixed too then in this regard, I copied it from there.

**Comment by Jason2866** [comment]
So i will remove the not needed fixes. I have a board with the ESP32-PICO-V3-02
and i know 100%.

**Comment by Jason2866** [comment]
qio flash mode is supported. i will change.

**Comment by Jason2866** [comment]
> Alright then, the [boards.txt](https://github.com/espressif/arduino-esp32/blob/68daea4a4a03ca0e10b84c3a34e40a371df11e69/boards.txt#L5776-L5777) might want to be fixed too then in this regard, I copied it from there.

Just take a quick look and saw thats not the only one which is wrong.
To be honest since I don't use Arduino IDE I don't feel much need for a long tedious error correction of this file

**Pull request merged**
